name: Pre-Production Checks
run-name: ${{ github.actor }}'s Flask API CI/CD
on:
    push:
        branches: [main]

jobs:
    api_ci:
        name: Flask HTTP API
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: '3.11.5'

            - name: Install requirements
              run: |
                  pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run Flask test
              run: | 
                  cd flask_api/tests
                  python -m pytest test.py